### ISSUE TITLE
Adding a new metadata to KoboData table

### ISSUE THREAD

**Issue by dianedetoeuf** [OpenFn/ConSoSci#151]
## Describe the bug
We need to add the citations for each dataset in the KoboData table. A new column called Citation has been added in this table. In Kobo forms you can add an "instance_name" in the settings page of the form, and I was thinkin we could add the citation there and have it mapped to the new Citation column.

I added the mapping to the BNS survey job, it runs successfully but the columns stays empty so it apparently doesn't find the value I've added into the "instance_name".

## To Reproduce
Example of successful run but nothing added in Citation: https://www.openfn.org/projects/p5x4g4/runs/rrkp6myd

### expression.js
See line 269 of https://www.openfn.org/projects/p5x4g4/jobs/jykm75

Any suggestion?

**Comment by aleksa-krolls** [comment]
@dianedetoeuf I don't see `instance_name` in the Message state: https://www.openfn.org/projects/p5x4g4/messages/ma9p848z

You said `instance_name` was added to Kobo form settings? Unfortunately when we fetch Kobo form submissions, the API only returns the form data... not form settings. So you'd either need to configure `instance_name` as a hidden value in form submissions (but I'm not sure this value will be automatically added to already submitted data)... AND/OR it can be another tag you specify when we get Kobo data. 
https://www.openfn.org/projects/p5x4g4/jobs/jvmjj9
```
{
        id: 'aVLz2FxFcw99cv89xNY46K',
        tag: 'bns_survey',
        name: 'BNS Makira 2021',
        owner: 'wcs_mamabaie',
        instance: 'XYZ'
      },
  ```
What do you think? Should we maybe add in this other tag? _OR_ can we determine the instance name based on the `instanceID`?... see L76: https://www.openfn.org/projects/p5x4g4/messages/ma9p848z

**Comment by dianedetoeuf** [comment]
ok, adding the tag seems the easiest, and I can call it directly citation so that we understand what it is. Can I also add this tag on the historical job? Will there be a way of updating only the KoboData able so that we don't have to re-process all the BNS/NRGT messages again? 

Thanks!

**Comment by dianedetoeuf** [comment]
Hi, I tried using a tag and reprocessed some of the historical forms but the citation field in the DB is still empty...
See
Line 27 historical job: https://github.com/OpenFn/ConSoSci/blob/master/bns/historical.js
Line 260: BNS survey : https://github.com/OpenFn/ConSoSci/blob/master/bns/survey.js

**Comment by aleksa-krolls** [comment]
@dianedetoeuf I'm realizing that we already were using a key called `tag` (e.g., `tag: 'bns_survey') in order to create the trigger for the OpenFn jobs. For example: 
```
{ id: 'aVcvLwLaG9ZCnQ9b7ACc2h', tag: 'bns_price', name: 'Prix Makira 2021', owner: 'wcs_mamabaie'}
```
I've therefore now added a different tagging key called `instance`...
https://github.com/OpenFn/ConSoSci/blob/b33dea0defbe1935ed5b06f2f74d4d207d94f375/bns/historical.js#L31

...and changed the `Citation` mapping in the BNS Survey to use this new key as the source value: 
https://github.com/OpenFn/ConSoSci/blob/5c495c4d71ddd0541803bbbf6eeea7fa2b5f51c2/bns/survey.js#L268

**Does this look right to you? If yes, can you please.... (1) add the new `instance` tag in the `historical.js` job for every form you want to re-sync? And then (2) run the historical job to test the output? (NOTE: I recommend testing with 1 form before re-syncing ALL historical forms)**

**Comment by dianedetoeuf** [comment]
Hi @aleksa-krolls, the mapping looks good and it seems to work when I test it but the citation column in the database is still empty...

**Comment by aleksa-krolls** [comment]
@dianedetoeuf What were you testing on? (I think we need to first re-fetch the data from the Kobo API in order to create new messages with this `instance` tag added.) Suggested next steps...

1. First update the `instance` tags of the relevant forms to re-sync here: https://www.openfn.org/projects/p5x4g4/jobs/jyxzzm
2. Then we can test by running this Historical Fetch job for 1 of these forms. Running this will create new Messages for this form with the `instance` tag appended to the Message body. 
3. Then we can see how the `bns/survey` job has processed this data to the DB. 
4. If it looks good, we can repeat step 2 but for all relevant forms.

**Comment by dianedetoeuf** [comment]
Hi, yes I've followed these steps yesterday: 
1. Added the instance tag line 27 of the historical job
2. Run this job for this socio eco survey EU form
3. Saw the incoming messages processed with bns/survey job, all successful, see for example this one https://www.openfn.org/projects/p5x4g4/messages/mrb764e8

But the citation column is still empty in the DB.

**Comment by ritazagoni** [comment]
`instance` tag is added to the message as expected https://www.openfn.org/projects/p5x4g4/messages/mrb764e8

**Comment by ritazagoni** [comment]
@aleksa-krolls haven't been able to find the source of the error

**Comment by aleksa-krolls** [comment]
@ritazagoni added to your backlog to triage again tomorrow

**Comment by ritazagoni** [comment]
@lakhassane `instance` tag is properly added to message, see for example https://www.openfn.org/projects/wcs/messages/061af216-3c30-74c3-bf92-b195cea465f1 However the expected `citation` column is not added to the DB with run https://www.openfn.org/projects/wcs/runs/061af216-450f-73e0-bc2d-b7a51112fa71

**Comment by aleksa-krolls** [comment]
@dianedetoeuf This has been resolved - see example successful run for submission `128044018`: https://www.openfn.org/projects/wcs/runs/061b20a4-d024-7ba9-bc23-6f1d872c16a4

Does it look okay in the DB now? 
Let us know if you need any help reprocessing, and if we can close this issue.

**Comment by dianedetoeuf** [comment]
Hi Aleksa, I've re-run the Lac Tele 20211115-aokQtdTGTnLW6omXRrf4ss dataset. The instance is in the messages but on the DB side the KoboData table still does not have any value in Citation...

**Comment by aleksa-krolls** [comment]
@lakhassane can you please help out? The mapping looks OK, but Diane says the dataValue for `instance` is still not outputting here: https://github.com/OpenFn/ConSoSci/blob/master/bns/survey.js#L276

Use this Message state to test (see LP for WCS Programs): 
https://www.openfn.org/projects/wcs/messages/061af216-3c30-74c3-bf92-b195cea465f1

**Comment by lakhassane** [comment]
@aleksa-krolls it's normal. When using `dataValue` it expects the data to be inside `state.data` which is not the case for `instance` (mapping to `Citation`).
It's the same "issue" for `DatasetName` and `DatasetOwner` because the value mapping to those columns is not `state.data` neither.

The solution would be to add in the first operation (maybe at line 45) => `cleanedSubmission.instance = instance;` and it will work.

I made the change

**Comment by aleksa-krolls** [comment]
Thanks @lakhassane! @dianedetoeuf I just re-ran this Message... can you review? (Thanks for your patience during all this back and forth.)
https://www.openfn.org/projects/wcs/runs/061b7341-dd99-7cda-9b96-3938998389b8

**Comment by dianedetoeuf** [comment]
Yes it worked! can we do the same for the BNS price job?

**Comment by dianedetoeuf** [comment]
and for the NRGT jobs? 
I can try adding it myself. :)
thank you!

**Comment by aleksa-krolls** [comment]
@dianedetoeuf okay cool, here is Mamadou's commit: https://github.com/OpenFn/ConSoSci/commit/80e6bc85e3a73e412d44f425c60ff4ae25d07e0b

Keep us posted if you get stuck, and we can re-open the issue.

**Comment by dianedetoeuf** [comment]
All green checks =) !
